### ISSUE TITLE
partTypeIdentifier of non-pluggable connectors needs a rule to be filled

### ISSUE THREAD

**Issue by niloda** [openBackhaul/equipment#2]
According to IEEE 802.3, register PHY 3 contains the manufacturer's model number in the bits 9 to 4. This 6-bit field can contain a binary number from 0b000000 to 0b111111 (or a decimal number from 0 to 63)

The YANG model provides partTypeIdentifier as a string to contain the model number, therefore it is necessary to define a rule to translate the binary number into a string.

Proposed solution:
translating from binary number to decimal number, for example:
  0b100111 will be translate  as string "39"
  0b001010 vil be translate as string "10"
putting the rule into the attribute description.

**Comment by openBackhaul** [comment]
Danilo commented in a separate email:
"
The issue referred to previous schemes for representing the physical structure of the device.

Soldered RJ45 interfaces were originally thought to be equipment plugged into hoders representing the physical connectors. 
The old WireEquipment document (in chapter 8 "Information") stated: "For non-pluggable connectors (like e.g. soldered RJ-45), this shall include at least the following information: ...".

In that case it would have been necessary to fill in the parameter partTypeIdentifier of actual-equipment and expected-equipment with the manufacturer's model number of the PHY which is a binary number as opposed to the manufacturer's model number of an SFP which is a string.
Hence the need to formalize a translation from binary number to string.

**With the latest decisions on HW representation, the issue is obsolete and can be closed without doing anything.**
"
